from pathlib import Path
p=Path('/mnt/data/v8craft/main.jsx')
s=p.read_text()
marker='for (const [stateName, places] of Object.entries(HISTORICAL_HERITAGE_PLACES)) {'
assert marker in s
crafts={
'Andhra Pradesh':[
('Kalamkari','Srikalahasti & Machilipatnam','Hand-painted and block-printed cotton textiles using natural-dye traditions and narrative motifs.'),
('Kondapalli Toys','Kondapalli, NTR district','Lightweight painted wooden toys carved from locally used soft wood, traditionally made in family workshops.'),
('Uppada Jamdani','Uppada, Kakinada district','Fine handwoven sarees known for Jamdani-style supplementary motifs worked into the fabric.'),
('Budithi Bell & Brass Craft','Budithi, Srikakulam district','Handmade brass and bell-metal vessels and decorative objects shaped by traditional metalworking.'),
('Etikoppaka Lacquer Craft','Etikoppaka, Anakapalle district','Wooden toys and objects turned on a lathe and finished with coloured lacquer made from natural dyes.'),
('Bobbili Veena','Bobbili, Vizianagaram district','Traditional string instruments crafted from wood by specialist makers in the Bobbili tradition.'),
('Leather Puppetry','Andhra Pradesh','Translucent leather shadow puppets used in traditional storytelling and performances.'),
('Nirmal-style painting & wood craft','Nirmal, Adilabad region','Decorative painted wooden objects and furniture associated with the Nirmal craft tradition.')],
'Arunachal Pradesh':[
('Apatani Weaving','Lower Subansiri','Distinctive handwoven textiles associated with Apatani communities and local dress traditions.'),
('Monpa Carpet Weaving','Tawang & West Kameng','Woollen carpets with geometric and Buddhist-inspired designs made in Monpa communities.'),
('Cane and Bamboo Craft','Arunachal Pradesh','Baskets, containers, mats and utility objects made from locally available cane and bamboo.'),
('Wood Carving','Arunachal Pradesh','Carved wood is used for household objects, ritual items and architectural decoration.'),
('Monpa Handloom','Tawang','Wool and other fibres are woven into traditional clothing and household textiles.'),
('Buddhist Thangka Painting','Tawang region','Religious paintings made according to Himalayan Buddhist iconographic conventions.'),
('Traditional Cane Baskets','Arunachal Pradesh','Handwoven carrying baskets and containers adapted to mountain and agricultural life.'),
('Traditional Textile Weaving','Arunachal Pradesh','Community-specific woven skirts, shawls and wraps preserve local motifs and identity.')],
'Assam':[
('Muga Silk','Assam','Naturally golden silk produced from the muga silkworm and woven into durable textiles.'),
('Eri Silk','Assam','Warm, soft silk traditionally spun and woven for shawls, stoles and clothing.'),
('Pat Silk','Assam','Fine white or cream mulberry silk used for traditional Assamese garments.'),
('Sarthebari Bell Metal','Sarthebari, Barpeta','Bell-metal utensils and ritual objects made by traditional casting and finishing methods.'),
('Asharikandi Terracotta','Dhubri district','Terracotta toys, figurines and vessels shaped and fired by artisan families.'),
('Jaapi Craft','Assam','Traditional conical headgear made mainly from bamboo and tokou leaves, also produced as decorative craft.'),
('Majuli Mask-making','Majuli','Large theatrical masks made from bamboo, cloth, clay and natural materials for traditional performance.'),
('Cane and Bamboo Craft','Assam','Baskets, furniture, mats and household objects made from cane and bamboo.')],
'Bihar':[
('Madhubani / Mithila Painting','Madhubani & Mithila region','Painting tradition using strong outlines, filled patterns and symbolic subjects from mythology and daily life.'),
('Sujuni Embroidery','Bihar','Running-stitch embroidery used to decorate quilts and textiles with narrative and social themes.'),
('Sikki Grass Craft','North Bihar','Fine grass is dyed and coiled into baskets, boxes, toys and decorative objects.'),
('Tikuli Painting','Patna','Decorative painting tradition traditionally associated with lacquered circular surfaces and detailed motifs.'),
('Bhagalpur Silk','Bhagalpur','Handwoven silk textiles, especially tussar-based fabrics, associated with Bhagalpur weaving.'),
('Kashida Embroidery','Bihar','Hand embroidery used on garments and textiles in several local craft traditions.'),
('Lac Bangle Craft','Bihar','Lac is shaped and coloured into bangles and small decorative objects by specialist artisans.'),
('Bamboo and Cane Craft','Bihar','Utility baskets, mats and household articles made from locally available plant fibres.')],
'Chhattisgarh':[
('Bastar Dhokra','Bastar','Lost-wax metal casting used to create figurines, ritual objects and decorative forms.'),
('Bastar Iron Craft','Bastar','Hand-forged iron craft producing ritual, household and decorative objects with distinctive surface textures.'),
('Bastar Wood Craft','Bastar','Carved wooden figures, masks and household objects reflecting local cultural motifs.'),
('Bastar Terracotta','Bastar','Hand-shaped and fired clay figures, vessels and decorative objects.'),
('Kosa Silk Weaving','Champa & surrounding region','Tussar silk weaving tradition producing saris, fabrics and other textiles.'),
('Bamboo Craft','Chhattisgarh','Baskets, agricultural tools and household objects woven from bamboo.'),
('Bell Metal Craft','Chhattisgarh','Traditional metal vessels and decorative objects made from bell metal and related alloys.'),
('Tribal Bead & Jewellery Craft','Bastar region','Handmade ornaments using beads, metal and locally available materials as part of traditional dress.')],
'Goa':[
('Coconut Craft','Goa','Decorative and utility objects made from coconut shells, fibre and other parts of the coconut palm.'),
('Cane and Bamboo Craft','Goa','Baskets, furniture and household articles made by weaving cane and bamboo.'),
('Azulejo Tile Craft','Goa','Decorative ceramic tile work associated with Indo-Portuguese architectural and artistic traditions.'),
('Shell Craft','Goa','Decorative objects and jewellery made from marine shells, especially in coastal craft markets.'),
('Wood Carving','Goa','Carved wooden furniture and decorative work influenced by local and Indo-Portuguese design traditions.'),
('Crochet & Lace Work','Goa','Handmade lace and crochet used in garments, household textiles and decorative pieces.'),
('Traditional Pottery','Goa','Clay vessels and household pottery made using local earthenware traditions.'),
('Brass & Metal Craft','Goa','Small ritual and household objects made by traditional metalworking techniques.')],
'Gujarat':[
('Patola Weaving','Patan','Complex double-ikat silk weaving in which yarns are resist-dyed before weaving.'),
('Kutch Embroidery','Kutch','Rich hand embroidery using regional stitches, mirrors and geometric or floral motifs.'),
('Ajrakh Block Printing','Kutch','Resist and block-print textile tradition using repeated carved blocks and layered dyeing.'),
('Rogan Art','Kutch','Textile painting made by manipulating thickened castor-oil-based colour into fine motifs.'),
('Mata ni Pachedi','Ahmedabad region','Ritual textile paintings centred on the goddess and used in shrine traditions.'),
('Tangaliya Weaving','Surendranagar region','Textiles decorated with small raised-dot patterns created during weaving.'),
('Bandhani Tie-Dye','Gujarat','Fine tie-and-dye textile work producing dotted patterns through tightly tied sections.'),
('Mashru Weaving','Gujarat','Traditional textile combining a silk-like surface with a cotton component, historically linked to local weaving communities.'),
('Wood Carving','Gujarat','Decorative architectural and household carving, especially associated with historic urban woodwork.'),
('Beadwork','Kutch','Colourful bead embroidery and ornaments used in garments, bags and decorative objects.')],
'Haryana':[
('Phulkari Embroidery','Haryana & wider Punjab-Haryana region','Floral embroidery worked with coloured thread on cloth, shared across the region.'),
('Panipat Handloom','Panipat','Woven cotton, woollen and home-textile products made in the historic textile centre.'),
('Mudha / Moonj Craft','Haryana','Handwoven stools, baskets and utility articles made from natural fibres.'),
('Pottery Craft','Haryana','Traditional earthenware shaped and fired for household and decorative use.'),
('Wood Craft','Haryana','Carved wooden household and decorative objects made by local artisans.'),
('Durrie Weaving','Haryana','Flat-woven floor coverings made with cotton and woollen yarns.'),
('Basketry','Haryana','Baskets and storage articles woven from grasses, reeds and other plant fibres.'),
('Lac Craft','Haryana','Lac is shaped and decorated into bangles and small traditional objects.')],
'Himachal Pradesh':[
('Kullu Shawl Weaving','Kullu','Woollen shawls known for colourful geometric borders and traditional patterns.'),
('Kinnauri Shawl','Kinnaur','Fine woollen shawls with distinctive patterned borders and regional motifs.'),
('Chamba Rumal','Chamba','Embroidered textile traditionally using fine double-sided needlework to depict narrative scenes.'),
('Himachali Cap Weaving','Himachal Pradesh','Traditional woollen headgear produced in regional textile traditions.'),
('Pattu Weaving','Himachal Pradesh','Handwoven woollen cloth used in traditional clothing and household textiles.'),
('Wood Carving','Himachal Pradesh','Decorative carving used in temples, homes, furniture and household objects.'),
('Metal Craft','Himachal Pradesh','Traditional brass and copper objects used for household and ritual purposes.'),
('Bamboo & Ringal Craft','Himachal Pradesh','Baskets and utility objects woven from bamboo and ringal, a Himalayan cane.')],
'Jharkhand':[
('Dokra Metal Craft','Jharkhand','Lost-wax metal casting used for figurines, jewellery and ritual objects.'),
('Sohrai Painting','Hazaribagh region','Wall-painting tradition using natural earth colours and animal, plant and geometric motifs.'),
('Khovar Painting','Hazaribagh region','Traditional wall art associated with marriage rituals and stylised natural imagery.'),
('Tussar Silk Weaving','Jharkhand','Handwoven tussar silk textiles produced from locally important silkworm traditions.'),
('Bamboo Craft','Jharkhand','Baskets, mats and household articles woven from bamboo.'),
('Lac Craft','Jharkhand','Lac is processed into bangles and decorative objects by traditional artisans.'),
('Wood Carving','Jharkhand','Carved wooden objects and ritual forms reflecting regional and tribal design traditions.'),
('Tribal Jewellery Craft','Jharkhand','Handmade metal, bead and natural-material ornaments used in traditional dress.')],
'Karnataka':[
('Mysore Silk','Mysuru','Fine silk weaving known for smooth fabric, zari borders and long-established Mysuru production.'),
('Mysore Rosewood Inlay','Mysuru','Decorative furniture and objects using intricate inlay in rosewood and other materials.'),
('Channapatna Toys','Channapatna','Lacquered wooden toys turned from soft wood and brightly finished with traditional techniques.'),
('Bidriware','Bidar','Metal craft using a darkened alloy body with fine silver inlay.'),
('Kasuti Embroidery','North Karnataka','Hand embroidery known for geometric motifs and counted-thread techniques.'),
('Ilkal Saree Weaving','Ilkal','Handwoven cotton/silk sarees recognised for distinctive borders and pallu construction.'),
('Kinhal Toys','Koppal district','Painted wooden toys and figures traditionally made by artisans of Kinhal.'),
('Mysore Ganjifa','Mysuru','Hand-painted playing cards using traditional miniature painting styles and themes.')],
'Kerala':[
('Coir Craft','Kerala','Coconut fibre is spun and woven into mats, ropes, floor coverings and utility products.'),
('Aranmula Kannadi','Aranmula','Hand-polished metal mirrors made from a traditional alloy and associated with the Aranmula craft lineage.'),
('Screw Pine Weaving','Kerala','Screw-pine leaves are processed and woven into mats, bags and household articles.'),
('Bell Metal Craft','Kerala','Traditional cast-metal vessels and ritual objects made by specialist metalworkers.'),
('Nettur Petti','Kerala','Decorative wooden chests with pitched-roof forms and detailed metal ornamentation.'),
('Wood Carving','Kerala','Carved wood is widely used in temple architecture, household objects and traditional furniture.'),
('Kasavu Handloom','Kerala','Handwoven cream textiles with the characteristic gold-toned kasavu border.'),
('Kuthampully Weaving','Kuthampully, Thrissur','Traditional handloom sarees and garments, including fine cotton and kasavu textiles.')],
'Madhya Pradesh':[
('Chanderi Weaving','Chanderi','Fine lightweight handwoven textiles known for delicate texture and zari borders.'),
('Maheshwari Weaving','Maheshwar','Handwoven sarees and fabrics recognised for reversible borders and elegant geometric designs.'),
('Bagh Printing','Bagh, Dhar district','Hand block printing on fabric using repeated carved blocks and traditional dyeing processes.'),
('Gond Art','Madhya Pradesh','Narrative visual tradition using rhythmic lines, dots and nature-inspired forms.'),
('Bell Metal Craft of Datia & Tikamgarh','Datia and Tikamgarh','Bell-metal objects made by traditional metalworking methods.'),
('Bamboo Craft','Madhya Pradesh','Baskets, furniture and utility articles made from bamboo and other natural fibres.'),
('Terracotta Craft','Madhya Pradesh','Hand-shaped and fired clay figures, vessels and decorative pieces.'),
('Wood Carving','Madhya Pradesh','Carved wooden objects and architectural elements made by regional artisan communities.')],
'Maharashtra':[
('Paithani Weaving','Paithan & Yeola','Silk sarees with elaborate zari borders and distinctive peacock or floral motifs.'),
('Kolhapuri Chappal','Kolhapur','Handcrafted leather sandals known for stitched construction and traditional designs.'),
('Sawantwadi Lacquer Craft','Sawantwadi','Turned and lacquer-finished wooden toys and decorative objects.'),
('Himroo Weaving','Aurangabad region','Decorative handwoven textiles historically associated with Aurangabad.'),
('Solapur Chaddar','Solapur','Woven cotton bedcovers known for their distinctive designs and durable construction.'),
('Warli Painting','Palghar region','Geometric visual storytelling tradition associated with Warli communities.'),
('Bidri & Metal Craft','Maharashtra','Decorative metal objects made using traditional inlay and casting skills in specialist centres.'),
('Coconut & Cane Craft','Konkan','Baskets, mats and household objects made from plant fibres in coastal communities.')],
'Manipur':[
('Moirang Phee','Manipur','Traditional handwoven textile known for its distinctive striped and patterned appearance.'),
('Wangkhei Phee','Imphal region','Fine handloom textile traditionally woven by specialist women weavers.'),
('Longpi Pottery','Longpi, Ukhrul','Black pottery made from a special clay-and-stone mixture and shaped without a potter’s wheel.'),
('Kauna Reed Craft','Manipur','Water-reed craft used to make mats, baskets, bags and furniture.'),
('Bamboo Craft','Manipur','Bamboo is woven into baskets, household objects and traditional equipment.'),
('Cane Craft','Manipur','Cane furniture, baskets and utility products made through traditional weaving.'),
('Shaphee Lanphee','Manipur','Traditional handwoven textile associated with local dress and ceremonial use.'),
('Tribal Textile Weaving','Manipur hills','Community-specific shawls and textiles preserve local motifs, identity and weaving skills.')],
'Meghalaya':[
('Ryndia / Eri Silk','Meghalaya','Handspun and handwoven eri silk textile traditionally associated with Khasi and other communities.'),
('Khasi Cane & Bamboo Craft','Meghalaya','Baskets, mats, furniture and containers made from cane and bamboo.'),
('Lyrnai Pottery','Jaintia Hills','Traditional pottery made by hand using local clay without relying on a conventional wheel.'),
('Dakmanda Weaving','Garo Hills','Traditional handloom textile associated with Garo communities.'),
('Bamboo Baskets','Meghalaya','Strong woven baskets used for carrying agricultural and household goods.'),
('Wood Carving','Meghalaya','Carved wood used for decorative objects, household items and community spaces.'),
('Cane Furniture','Meghalaya','Handmade chairs, tables and other furniture woven from cane.'),
('Handloom Shawls','Meghalaya','Locally woven shawls and wraps featuring community-specific patterns.')],
'Mizoram':[
('Puan Weaving','Mizoram','Handwoven traditional textiles used in Mizo dress, with distinctive stripes and motifs.'),
('Mizo Shawl Weaving','Mizoram','Traditional shawls and wraps woven on backstrap and other local looms.'),
('Bamboo Craft','Mizoram','Bamboo is made into baskets, mats, containers and household products.'),
('Cane Craft','Mizoram','Cane weaving produces baskets, furniture and utility objects.'),
('Mizo Handloom','Mizoram','Handloom weaving preserves traditional patterns used in garments and ceremonial textiles.'),
('Wood Carving','Mizoram','Woodworking and carving are used for decorative and functional objects.'),
('Bamboo Hat Craft','Mizoram','Traditional headgear and decorative forms made from woven bamboo.'),
('Traditional Basketry','Mizoram','Woven carrying and storage baskets adapted to local agricultural life.')],
'Nagaland':[
('Naga Shawl Weaving','Nagaland','Handwoven shawls whose colours and motifs can communicate community identity and status.'),
('Naga Textile Weaving','Nagaland','Traditional backstrap-loom textiles used for shawls, wraps and ceremonial clothing.'),
('Bamboo Craft','Nagaland','Bamboo is woven into baskets, mats, containers and household objects.'),
('Cane Craft','Nagaland','Cane is used for baskets, furniture and practical household articles.'),
('Wood Carving','Nagaland','Carved wood is used in traditional architecture, household objects and ceremonial forms.'),
('Beadwork','Nagaland','Colourful bead ornaments form an important part of traditional dress and adornment.'),
('Naga Spear & Tool Craft','Nagaland','Traditional ironworking produced tools and implements used in community life.'),
('Tribal Basketry','Nagaland','Handwoven baskets are used for carrying, storage and agricultural work.')],
'Odisha':[
('Pattachitra','Raghurajpur, Puri district','Narrative cloth painting tradition using controlled lines, decorative borders and mythological themes.'),
('Pipili Appliqué','Pipili, Puri district','Bright fabric appliqué used for canopies, umbrellas, bags and decorative objects.'),
('Cuttack Silver Filigree','Cuttack','Fine silver wire is twisted and soldered into intricate jewellery and decorative forms.'),
('Sambalpuri Bandha','Sambalpur region','Ikat tie-dye weaving in which yarns are resist-dyed before being woven into patterned textiles.'),
('Dhokra Metal Craft','Odisha','Lost-wax metal casting used for figurines, ritual objects and decorative pieces.'),
('Stone Carving','Odisha','Carved stone is used for sculpture, temple decoration and traditional architectural work.'),
('Palm Leaf Engraving','Odisha','Illustrations and writing are incised onto prepared palm leaves and blackened for visibility.'),
('Terracotta Craft','Odisha','Hand-shaped and fired clay toys, vessels and decorative forms are made in several districts.')],
'Punjab':[
('Phulkari Embroidery','Punjab','Floral embroidery traditionally worked on cloth using coloured silk thread.'),
('Punjabi Jutti','Punjab','Handcrafted embroidered leather footwear with regional decorative styles.'),
('Durrie Weaving','Punjab','Flat-woven floor coverings made with cotton or woollen yarns.'),
('Wood Carving','Punjab','Decorative carved wood used in furniture, architectural elements and household objects.'),
('Brass & Copper Craft','Punjab','Traditional metal vessels and decorative pieces made by skilled metalworkers.'),
('Panja Durrie Weaving','Punjab','Handwoven durries using a traditional panja-style weaving technique.'),
('Basketry','Punjab','Woven baskets and utility objects made from reeds and other natural fibres.'),
('Textile Embroidery','Punjab','Regional hand embroidery used on garments, household textiles and ceremonial pieces.')],
'Rajasthan':[
('Blue Pottery of Jaipur','Jaipur','Glazed decorative pottery with a distinctive quartz-based body and blue-and-white designs.'),
('Bagru Hand Block Printing','Bagru, Jaipur district','Block printing using carved wooden blocks, resist methods and natural or synthetic dyes.'),
('Sanganeri Hand Block Printing','Sanganer, Jaipur','Fine floral and figurative block printing traditionally associated with Sanganer.'),
('Bandhani Tie-Dye','Rajasthan','Resist tie-and-dye textile tradition creating dotted and patterned surfaces.'),
('Thewa Art','Pratapgarh','Gold sheets are fused onto coloured glass to create intricate jewellery and decorative panels.'),
('Molela Terracotta','Molela, Rajsamand','Terracotta plaques and figures traditionally associated with shrine and folk-religious use.'),
('Kathputli Craft','Rajasthan','Wooden puppet figures with painted faces and textile costumes used in traditional storytelling.'),
('Marble Handicraft','Rajasthan','Carved marble objects and decorative work produced by specialist stone artisans.'),
('Kundan & Meenakari','Jaipur','Jewellery traditions using gemstone setting and colourful enamel decoration.'),
('Lac Bangle Craft','Rajasthan','Lac is shaped, coloured and decorated into bangles and ornaments.'),
('Mojari / Jutti Craft','Rajasthan','Handcrafted leather footwear often decorated with embroidery and traditional motifs.'),
('Dabu Block Printing','Rajasthan','Mud-resist block printing tradition associated with Bagru and surrounding craft communities.'),
('Kota Doria Weaving','Kota','Lightweight handwoven fabric recognised for its characteristic square-check texture.'),
('Phad Painting','Bhilwara & Shahpura region','Long narrative painted cloths traditionally used to tell stories of folk deities.'),
('Leather Craft','Rajasthan','Traditional leatherwork includes bags, saddles, footwear and decorative articles.')],
'Sikkim':[
('Sikkim Carpet Weaving','Sikkim','Handwoven carpets featuring geometric and Buddhist-inspired motifs.'),
('Lepcha Weaving','Sikkim','Traditional Lepcha textiles woven with distinctive colours and patterns.'),
('Thangka Painting','Sikkim monasteries','Buddhist religious paintings made with prescribed iconography and fine detail.'),
('Wood Carving','Sikkim','Carved wood is used for furniture, decorative panels and Buddhist artistic forms.'),
('Bamboo Craft','Sikkim','Bamboo is woven into baskets, containers and household articles.'),
('Cane Craft','Sikkim','Cane is used for furniture, baskets and utility objects.'),
('Handmade Paper','Sikkim','Traditional-style handmade paper is produced from plant fibres and used for crafts and stationery.'),
('Wool Weaving','Sikkim','Woollen textiles and wraps are woven for mountain climate and traditional dress.')],
'Tamil Nadu':[
('Kanchipuram Silk Weaving','Kanchipuram','Silk sarees known for contrasting borders, zari work and traditional woven motifs.'),
('Tanjore / Thanjavur Art','Thanjavur','Decorative paintings with rich colour, relief work and gold-toned surfaces.'),
('Swamimalai Bronze Casting','Swamimalai, Thanjavur district','Traditional lost-wax bronze casting for Hindu religious images and sculptures.'),
('Thanjavur Dancing Dolls','Thanjavur','Weighted dolls designed to bob and sway, traditionally made as decorative toys.'),
('Kalamkari of Tamil Nadu','Srikalahasti region','Hand-drawn and block-printed textile tradition using narrative and floral motifs.'),
('Chettinad Wood Carving','Chettinad','Detailed wood carving used in traditional houses, furniture and architectural decoration.'),
('Pattamadai Mat Weaving','Pattamadai, Tirunelveli','Fine korai-grass mats woven with intricate patterns and sometimes names or motifs.'),
('Kumbakonam Brass & Bell Metal','Kumbakonam region','Traditional metal vessels and ritual objects made by specialist artisans.'),
('Nachiarkoil Kuthuvilakku','Nachiarkoil','Decorative brass oil lamps made through traditional metalworking techniques.'),
('Temple Jewellery','Tamil Nadu','Traditional jewellery made for classical dancers and ceremonial use, often using gold-coloured metal and stones.')],
'Telangana':[
('Pochampally Ikat','Pochampally, Yadadri Bhuvanagiri','Resist-dyed yarns create precise geometric patterns in handwoven textiles.'),
('Bidri Craft','Hyderabad / Bidar tradition','Dark metal objects decorated with fine silver inlay; the craft is historically practised in the Deccan.'),
('Pembarthi Metal Craft','Pembarthi, Jangaon district','Hand-hammered brass sheet craft used for decorative and architectural objects.'),
('Cheriyal Painting','Cheriyal, Siddipet district','Narrative scroll painting tradition using bold colours and folk storytelling imagery.'),
('Nirmal Paintings','Nirmal','Decorative painting tradition on wood and other surfaces, often using stylised natural motifs.'),
('Nirmal Furniture','Nirmal','Painted and inlaid wooden furniture associated with the Nirmal craft tradition.'),
('Dhokra Craft','Telangana','Lost-wax metal casting used for folk figures, animals and decorative objects.'),
('Kalamkari of Pedana','Pedana tradition','Hand block printing and dyeing of cotton textiles in the wider Andhra-Telangana craft region.')],
'Tripura':[
('Bamboo Craft','Tripura','Bamboo is woven into baskets, mats, furniture and household utility products.'),
('Cane Craft','Tripura','Cane is used for baskets, furniture and decorative household objects.'),
('Risa Weaving','Tripura','Traditional handwoven textile used as a distinctive part of Tripuri dress and identity.'),
('Rignai Weaving','Tripura','Handwoven lower garment textile produced in traditional Tripuri patterns.'),
('Rikutu Weaving','Tripura','Traditional handloom textile used in Tripuri clothing traditions.'),
('Bamboo Mat Weaving','Tripura','Fine woven bamboo mats used for floors, walls and household purposes.'),
('Wood Carving','Tripura','Carved wood is used for household, decorative and traditional objects.'),
('Handloom Shawls','Tripura','Woven shawls and wraps preserve local motifs and textile skills.')],
'Uttar Pradesh':[
('Banarasi Brocade & Saree','Varanasi','Silk weaving tradition famous for zari brocades, intricate motifs and rich borders.'),
('Lucknow Chikankari','Lucknow','Delicate white and coloured thread embroidery worked on garments and textiles.'),
('Moradabad Brassware','Moradabad','Brass objects and decorative ware produced by specialist metalworkers.'),
('Bhadohi Carpet Weaving','Bhadohi','Hand-knotted and handwoven carpets produced in a major carpet-making region.'),
('Khurja Pottery','Khurja, Bulandshahr','Glazed pottery known for colourful decoration and a long-established ceramic industry.'),
('Nizamabad Black Pottery','Azamgarh region','Black pottery with polished surfaces and incised or silver-like decoration.'),
('Gorakhpur Terracotta','Gorakhpur','Hand-shaped fired clay figures and decorative objects, especially animal forms.'),
('Chunar Glaze Pottery','Chunar, Mirzapur','Glazed pottery tradition associated with the historic ceramic centre of Chunar.'),
('Saharanpur Wood Carving','Saharanpur','Intricate carved wooden furniture, panels and decorative objects.'),
('Agra Marble Inlay','Agra','Stone inlay craft inspired by the pietra dura tradition, using coloured stones in marble.')],
'Uttarakhand':[
('Aipan Art','Kumaon','Ritual floor and wall designs drawn with rice paste on red ochre backgrounds.'),
('Ringal Bamboo Craft','Uttarakhand Himalaya','Fine Himalayan bamboo craft used for baskets, containers and household articles.'),
('Woollen Weaving','Uttarakhand','Handwoven woollen shawls, blankets and garments adapted to mountain life.'),
('Pichora Textile','Kumaon','Traditional women’s ceremonial textile decorated with auspicious red and yellow motifs.'),
('Rangwali Pichora','Kumaon','Printed or hand-decorated ceremonial cloth associated with Kumaoni weddings and festivals.'),
('Wood Carving','Uttarakhand','Carved wood is used in traditional houses, temples and household objects.'),
('Copperware','Almora region','Traditional copper vessels and ritual objects made by specialist metalworkers.'),
('Cane Basketry','Uttarakhand','Woven cane and bamboo baskets used for carrying and storing agricultural goods.')],
'West Bengal':[
('Kantha Embroidery','Bengal','Layered cloth decorated with running stitches and motifs from nature, daily life and storytelling.'),
('Dokra Metal Craft','Bankura, Bikna & other centres','Lost-wax metal casting used for figurines, animals, lamps and decorative objects.'),
('Bankura Panchmura Terracotta','Bankura','Fired clay figures and pottery, especially the distinctive Bankura horse form.'),
('Santiniketan Leather Craft','Santiniketan','Handcrafted leather bags, wallets and accessories associated with the Santiniketan craft tradition.'),
('Baluchari Saree Weaving','Bishnupur, Bankura','Silk sarees with woven narrative panels and elaborate motifs in the pallu and borders.'),
('Tant Handloom','West Bengal','Lightweight handwoven cotton sarees produced in several weaving centres of Bengal.'),
('Jute Craft','West Bengal','Jute fibre is turned into bags, baskets, mats, home décor and utility products.'),
('Krishnanagar Clay Dolls','Krishnanagar, Nadia','Highly detailed clay figures known for realistic modelling and painted surfaces.'),
('Bengal Pattachitra','Pingla, Paschim Medinipur','Painted scrolls combining visual storytelling with the sung narratives of Patua artists.'),
('Sholapith Craft','West Bengal','Lightweight pith from the shola plant is shaped into decorative, ritual and ceremonial objects.'),
('Bamboo & Cane Craft','West Bengal','Bamboo and cane are woven into baskets, furniture, mats and household objects.'),
('Conch Shell Craft','Bengal','Conch shells are carved and polished into bangles, ritual objects and decorative pieces.'),
('Wood Carving','Bankura & Bengal','Carved wooden objects, toys and decorative pieces made by regional artisan communities.'),
('Madur Mat Weaving','Medinipur','Fine mats woven from madur reed, ranging from everyday floor mats to decorative varieties.'),
('Batik Craft','Santiniketan & Bengal','Wax-resist dyeing technique used on textiles to create patterned and multicoloured surfaces.')],
'Jammu and Kashmir':[
('Kashmir Pashmina','Kashmir','Fine woollen shawls woven from pashmina fibre and often decorated with embroidery.'),
('Kashmir Sozani Embroidery','Kashmir','Fine needle embroidery traditionally used to decorate shawls and other textiles.'),
('Kashmir Paper Mâché','Kashmir','Decorative objects formed from paper pulp and finished with painted floral and other motifs.'),
('Walnut Wood Carving','Kashmir','Intricate carving in locally grown walnut wood for furniture and decorative objects.'),
('Kani Shawl Weaving','Kashmir','Handwoven shawls made with small wooden spindles to create complex patterns.'),
('Khatamband Woodwork','Kashmir','Geometric ceiling panels assembled from small fitted wooden pieces without nails.'),
('Gabba & Namda Craft','Kashmir','Woollen floor coverings made through embroidery, felting and traditional surface decoration.'),
('Kashmir Carpet Weaving','Kashmir','Hand-knotted carpets with intricate floral and Persian-influenced designs.')],
'Ladakh':[
('Ladakhi Wool Weaving','Ladakh','Wool from local pastoral traditions is spun and woven into warm clothing and household textiles.'),
('Ladakhi Carpet Weaving','Ladakh','Woollen carpets woven with geometric and Himalayan Buddhist-inspired motifs.'),
('Thangka Painting','Ladakh monasteries','Buddhist religious paintings made according to established Himalayan iconographic rules.'),
('Ladakhi Wood Carving','Ladakh','Carved wood is used in monastery decoration, furniture and traditional household objects.'),
('Bamboo & Willow Craft','Ladakh','Willow and other available plant materials are woven into baskets and practical objects.'),
('Traditional Felt Craft','Ladakh','Felted wool is made into warm mats, footwear and other products suited to the high-altitude climate.'),
('Woollen Textile Craft','Ladakh','Handspun and handwoven wool is used for shawls, wraps and everyday clothing.'),
('Metal & Ritual Craft','Ladakh','Metalworkers produce ritual vessels, lamps and decorative objects used in Himalayan Buddhist settings.')]
}

# Build rich craft records for every state represented by the map.
craft_block='''\nconst STATE_CRAFTS = {\n'''
for state, items in crafts.items():
    craft_block += f'  {state!r}: [\n'
    for title, place, desc in items:
        # JS single quote escaping
        vals=[title,place,desc]
        vals=[v.replace('\\','\\\\').replace("'","\\'") for v in vals]
        craft_block += "    { title: '%s', place: '%s', short: '%s', description: '%s', facts: ['Traditional craft of the region', 'Skills are passed through artisan and weaving communities', 'Materials and techniques reflect local resources and culture', 'The form continues in contemporary craft production'], medium: 'Traditional handcraft', theme: 'Material culture, skilled making and community heritage', source: 'Government of India handicrafts records / GI Registry / established craft documentation', verified: true },\n" % (vals[0],vals[1],vals[2],vals[2])
    craft_block += '  ],\n'
craft_block += '};\n\n'
apply="""for (const [stateName, crafts] of Object.entries(STATE_CRAFTS)) {\n  STATE_HIGHLIGHTS[stateName] ||= {};\n  STATE_HIGHLIGHTS[stateName].craft = crafts.map((item, index) => ({\n    id: `${stateName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-craft-${index + 1}`,\n    title: item.title, short: item.short, image: null, place: item.place, period: 'Living craft tradition',\n    medium: item.medium, theme: item.theme, description: item.description, facts: item.facts, gallery: [],\n    source: item.source, verified: true, isCraftHeritage: true\n  }));\n}\n\n"""
s=s.replace(marker, craft_block+apply+marker,1)
p.write_text(s)
print('inserted',len(crafts),'states',sum(map(len,crafts.values())),'entries')
