from pathlib import Path
import json

D = {}
def add(state, items): D[state]=items

def it(title, place, short, facts):
    return {'title':title,'place':place,'short':short,'description':short,'facts':facts}

add('Andhra Pradesh', [
 it('Kalamkari', 'Srikalahasti & Machilipatnam', 'Hand-painted and block-printed cotton textile art known for narrative motifs and natural-dye traditions.', ['Srikalahasti is associated with hand-painted narrative work','Machilipatnam is known for block-printed Kalamkari','Themes include epics, deities, plants and decorative borders','Traditional processes use mordants and repeated dyeing']),
 it('Lepakshi Mural Painting', 'Lepakshi, Anantapur district', 'Vijayanagara-period temple paintings with rich colours, narrative scenes and ornamental detail.', ['Found in the Veerabhadra Temple complex','Associated with Vijayanagara-period art','Figures and decorative borders are major features','Painted ceilings preserve important historical imagery']),
 it('Tholu Bommalata', 'Andhra Pradesh', 'Traditional leather shadow-puppet art in which painted translucent figures are used for storytelling.', ['Uses perforated and painted leather puppets','Figures are manipulated behind a lighted screen','Stories traditionally draw on epics and local performance traditions','Recognised as a major Andhra leather-puppet tradition']),
 it('Leather Puppet Art', 'Andhra Pradesh', 'Decorative and performance-oriented leather figure making connected with shadow theatre.', ['Leather is cleaned, cut and perforated','Figures are painted with strong colours','Puppets are mounted on sticks for manipulation','Art is closely linked to storytelling performance']),
 it('Kondapalli Painted Toys', 'Kondapalli, NTR district', 'Lightweight painted wooden figures depicting people, animals, occupations and village scenes.', ['Made from locally used soft wood','Figures are carved in separate parts and joined','Traditional themes include village life and festival scenes','Painting gives the toys their distinctive visual character']),
])
add('Arunachal Pradesh', [
 it('Monpa Thangka Painting','Tawang & West Kameng','Buddhist devotional painting tradition using prescribed iconography, proportions and fine detail.',['Used in Himalayan Buddhist religious settings','Images follow established iconographic conventions','Mineral and organic pigments have traditionally been used','Painting can serve devotional and teaching purposes']),
 it('Monpa Wall Painting','Tawang region','Decorative Buddhist murals and painted architectural surfaces associated with monasteries and sacred spaces.',['Seen in monastery interiors and religious spaces','Motifs include Buddhist figures and symbolic designs','Requires careful preparation of the wall surface','Part of the visual environment of Himalayan Buddhist practice']),
 it('Aji Lhamu Mask Art','Arunachal Pradesh','Colourful masks and visual objects used in the Monpa Aji Lhamu masked theatre tradition.',['Aji Lhamu is a traditional Monpa theatre form','Masks help represent characters in performance','Costume, masks and movement work together','Tradition combines storytelling with ritual and community performance']),
 it('Wood Carving','Arunachal Pradesh','Carved wood used for household objects, architectural decoration and ritual or community purposes.',['Wood is a widely used local material','Motifs vary among communities','Carving skills are transmitted within artisan traditions','Objects range from utility pieces to decorative work']),
 it('Bamboo Decorative Art','Arunachal Pradesh','Bamboo is shaped into patterned and functional objects with strong regional visual traditions.',['Bamboo is locally abundant','Splitting, weaving and shaping are common techniques','Objects include baskets and household articles','Designs reflect local community practices']),
])
add('Assam', [
 it('Assamese Manuscript Painting','Assam','Illustrated manuscript art associated with Vaishnavite literary and religious culture.',['Manuscripts were traditionally prepared on sanchi or other writing materials','Illustrations accompany religious and literary texts','Vaishnavite institutions helped preserve the tradition','Figures and borders use stylised forms and colour']),
 it('Majuli Manuscript Painting','Majuli','Visual decoration and illustration associated with the manuscript culture of Majuli satras.',['Linked with Neo-Vaishnavite cultural institutions','Manuscripts preserve religious and literary texts','Illustrations can accompany narrative passages','Satras remain important custodians of the tradition']),
 it('Bhaona Mask Art','Majuli','Handmade masks used in Bhaona theatre, often representing mythological and animal characters.',['Masks are made for dramatic performance','They can be made from natural materials such as bamboo and cloth','Characters are linked to Vaishnavite theatre','Mask-making is closely associated with Majuli performance culture']),
 it('Assamese Folk Painting','Assam','Decorative painting traditions used in community, religious and festive contexts.',['Motifs draw from nature, mythology and local life','Traditional materials include natural pigments and handmade surfaces','Visual styles vary by community and occasion','Painting remains part of Assam’s wider folk-art heritage']),
 it('Ganjifa Card Art','Assam','Painted playing-card traditions preserved in parts of Assam and linked with older Indian card-making practices.',['Cards are individually painted','Themes can include figures and symbolic motifs','The craft combines illustration with card-making','It belongs to India’s wider Ganjifa tradition']),
])
add('Bihar', [
 it('Madhubani / Mithila Painting','Mithila region','Highly patterned folk painting tradition depicting deities, nature, rituals and social themes.',['Styles include Bharni, Kachni and Godna','Traditionally associated with wall and floor painting','Natural colours were historically important','Now widely practised on paper, cloth and other surfaces']),
 it('Kohbar Painting','Mithila region','Wedding-related painting tradition featuring symbolic plants, animals, fertility imagery and geometric designs.',['Traditionally associated with marriage spaces','Lotus, bamboo and fish are common symbolic motifs','The imagery relates to fertility, prosperity and auspiciousness','Closely connected with Mithila domestic ritual art']),
 it('Manjusha Art','Bhagalpur region','Narrative painting tradition associated with the worship of Bishahari and the Bihula-Bishahari story.',['Associated with Bhagalpur','Traditional images use elongated forms and bold colours','Bishahari worship is central to the tradition','Paintings can appear on paper and other surfaces today']),
 it('Tikuli Art','Patna region','Decorative painting tradition using bold outlines and intricate motifs, historically linked with hand-painted tikuli ornaments.',['Developed around Patna','Modern Tikuli art is painted on hard surfaces such as boards','Motifs include deities, women, festivals and decorative designs','The name relates to the traditional tikuli ornament']),
 it('Godna Painting','Mithila & Bihar tribal communities','Tattoo-inspired visual motifs adapted into painting and decorative art.',['Patterns echo traditional tattoo designs','Geometric and symbolic motifs are common','The style is associated with marginalised and tribal artistic traditions','Modern artists use paper and cloth as well as walls']),
])
add('Chhattisgarh', [
 it('Godna Art','Chhattisgarh','Tattoo-inspired geometric and symbolic designs represented in paintings and other visual forms.',['Motifs are linked with body-art traditions','Geometric repetition is common','Art can carry social and cultural symbolism','Practised within several tribal communities']),
 it('Bastar Tribal Painting','Bastar region','Folk and tribal visual art drawing on local nature, community life, deities and ritual imagery.',['Themes are rooted in community life','Natural forms and local symbols are common','Visual traditions vary among Bastar communities','Painting is often connected with festivals and domestic spaces']),
 it('Pithora-inspired Painting','Northern Chhattisgarh and neighbouring regions','Ritual wall-painting style connected with Adivasi visual traditions in central India.',['Pithora traditions are strongest among Rathwa and related communities','Horse figures are a major visual motif','Paintings can be connected with ritual vows and ceremonies','Regional forms vary across central India']),
 it('Bhil Visual Art','Chhattisgarh border regions','Decorative tribal imagery using repeated dots, lines, animals and nature motifs.',['Nature and animals are frequent subjects','Repeated dots can create texture and movement','Styles vary by community and artist','The work is part of wider central Indian tribal art traditions']),
 it('Bastar Wall Art','Bastar','Community wall decoration using geometric, floral and figurative motifs during domestic and festive occasions.',['Walls provide an important traditional surface','Motifs are adapted to local materials and customs','Women and community artists play important roles in many traditions','Designs can mark festive or ritual occasions']),
])
add('Goa', [
 it('Kaavi Art','Goa','Red-and-white laterite wall art made by incising designs into a lime-plaster surface.',['Strongly associated with Goa and parts of the Konkan','Uses a red laterite-derived background with white lime','Often decorates old homes and religious buildings','Geometric and floral patterns are common']),
 it('Goan Church Mural Art','Old Goa and Goa','Sacred wall and ceiling paintings shaped by local and European Christian visual traditions.',['Found in historic churches and chapels','Themes are largely Christian and devotional','Local materials and artisans influenced the visual style','Forms part of Goa’s Indo-European artistic heritage']),
 it('Azulejo Tile Art','Goa','Decorative ceramic tile art used in architectural interiors and public or domestic spaces.',['Portuguese influence is prominent','Tiles may carry figurative or floral imagery','Used as architectural decoration rather than only as standalone paintings','Now a recognisable part of Goa’s visual heritage']),
 it('Goan Folk Painting','Goa','Local decorative painting traditions drawing on festivals, religious imagery and everyday coastal life.',['Themes vary by community','Natural and commercial pigments are both used today','Decorative work appears on walls and objects','The tradition reflects Goa’s mixed cultural history']),
 it('Coconut Shell Art','Goa','Decorative objects and motifs made by shaping and polishing coconut shell.',['Uses an abundant coastal material','Shell is cleaned, cut and polished','Products include bowls and decorative objects','Represents a practical-to-artistic reuse tradition']),
])
add('Gujarat', [
 it('Mata ni Pachedi','Ahmedabad region','Ritual textile painting depicting the Mother Goddess and sacred narratives.',['Made on cloth for shrine use','The Vaghari community is strongly associated with the tradition','Red and black are prominent colours','Narrative scenes centre on the goddess and her sacred world']),
 it('Pithora Painting','Central/eastern Gujarat','Ritual wall painting associated with Rathwa, Bhilala and related Adivasi communities.',['Horses are a major motif','Paintings are connected with ritual vows and ceremonies','The work is traditionally created on prepared wall surfaces','It has a strong ceremonial rather than purely decorative role']),
 it('Rogan Art','Kutch','Textile painting made by manipulating thick castor-oil-based colour into fine raised designs.',['Traditionally associated with Nirona in Kutch','Paint is prepared from castor oil and pigments','A metal stylus or pointed tool helps place the colour','Tree-of-life and symmetrical motifs are well known']),
 it('Ajrakh Block Printing','Kutch','Complex resist and block-print textile art using repeated carved blocks and layered dyeing.',['Kutch is a major Ajrakh centre','Natural dyes and mordants have a long history in the craft','Multiple blocks create repeated patterns','Indigo and madder-derived reds are characteristic colours']),
 it('Bandhani Art','Gujarat','Tie-and-dye textile art made by tightly tying small sections of cloth before dyeing.',['Known for dotted patterns','Bhuj and Jamnagar are important centres','Multiple tying and dyeing stages can create complex patterns','Traditional garments include odhnis, sarees and turbans']),
 it('Patola Design Art','Patan','Highly intricate double-ikat textile design associated with Patan’s silk weaving tradition.',['Both warp and weft are resist-dyed before weaving','Precise alignment creates the final pattern','Traditional motifs include geometric and figurative forms','Patola is associated with Patan in north Gujarat']),
])
add('Haryana', [
 it('Phulkari Embroidery','Haryana & Punjab-Haryana region','Floral and geometric embroidery tradition shared across the wider Punjab-Haryana cultural region.',['Uses coloured silk thread on cloth','Floral motifs are especially common','Traditionally used for shawls, dupattas and household textiles','Regional styles vary across north-western India']),
 it('Sanjhi Paper Art','Haryana/Braj region','Intricate paper-cut stencil art depicting sacred and floral compositions.',['Made by cutting detailed paper stencils','Strongly associated with Krishna devotional imagery','Braj cultural areas span Haryana and neighbouring Uttar Pradesh','Designs can be used for ritual and decorative purposes']),
 it('Chowk Purna','Haryana','Decorative floor and threshold drawing tradition using simple geometric and auspicious motifs.',['Made on floors or entrances','Uses locally available powders or wet materials','Motifs can mark festivals and household ceremonies','Belongs to the wider North Indian floor-art tradition']),
 it('Haryanvi Folk Wall Painting','Haryana','Traditional decorative painting associated with village homes, festivals and domestic spaces.',['Floral and geometric motifs are common','Walls and household surfaces provide the canvas','Designs can be seasonal or ceremonial','Practices vary between communities and regions']),
 it('Decorative Pottery Painting','Haryana','Painted earthenware combining utility pottery with simple floral and geometric decoration.',['Pottery is shaped from local clay','Surfaces can be burnished or painted','Decorative motifs vary by artisan cluster','The tradition connects pottery with everyday visual culture']),
])
add('Himachal Pradesh', [
 it('Kangra Painting','Kangra region','Pahari miniature painting famous for lyrical landscapes, delicate figures and Krishna-Radha themes.',['Flourished under Kangra rulers in the 18th century','Often depicts Krishna, Radha and poetic themes','Fine lines and soft colours are characteristic','Part of the wider Pahari miniature tradition']),
 it('Guler Painting','Guler','Early Pahari miniature style known for naturalistic figures and refined drawing.',['Associated with the Guler court','Influenced later Kangra painting','Naturalistic portraiture is a notable feature','Developed strongly in the 18th century']),
 it('Chamba Rumal','Chamba','Double-sided embroidered textile art with narrative and devotional scenes.',['Uses fine embroidery on both sides of the cloth','Themes include Krishna, marriage scenes and epics','Associated with Chamba in Himachal Pradesh','The technique creates an almost painted appearance']),
 it('Chamba Miniature Painting','Chamba','Pahari miniature painting tradition depicting devotional, courtly and literary themes.',['Part of the Pahari school of painting','Uses fine brushes and detailed line work','Religious and court subjects are common','Connected with historic Chamba patronage']),
 it('Thangka Painting','Himachal Himalayan region','Buddhist devotional painting tradition practised in Himalayan communities.',['Used for teaching and meditation','Iconography follows established Buddhist conventions','Fine detail and controlled proportions are important','Related Himalayan traditions extend into neighbouring regions']),
])
add('Jharkhand', [
 it('Sohrai Painting','Hazaribagh region','Earth-pigment wall painting traditionally made around the Sohrai harvest and cattle festival.',['Strongly associated with Hazaribagh villages','Animals, plants and fertility motifs are common','Walls are a traditional painting surface','Women artists have played a major role in preserving the tradition']),
 it('Khovar Painting','Hazaribagh region','Wedding-associated wall painting tradition using geometric, plant and animal motifs.',['Traditionally linked with marriage houses','Natural pigments and clay surfaces are important','Motifs can include bamboo, birds and fertility symbols','Often created by women artists']),
 it('Jadopatia Painting','Jharkhand','Narrative scroll painting tradition associated with the Santhal cultural region.',['Scrolls are used for storytelling','Images may depict myths, social life and the afterlife','Jadopatia artists are associated with the tradition','Painting and oral narration work together']),
 it('Paitkar Painting','Amadubi, East Singhbhum','Scroll-based narrative painting tradition of eastern Jharkhand.',['Amadubi is a recognised centre','Paintings can depict mythological and social narratives','Scrolls are traditionally shown with oral narration','Natural and handmade materials have been used historically']),
 it('Godna Tribal Art','Jharkhand','Tattoo-inspired motifs translated into painting and decorative surfaces.',['Geometric patterns are common','Visual symbols can carry community meanings','The style is connected with tattoo traditions','Modern artists use paper and cloth as well as walls']),
])
add('Karnataka', [
 it('Mysore Painting','Mysuru region','Fine devotional painting tradition known for delicate line work, rich colours and gold leaf.',['Flourished under Mysore court patronage','Gold leaf is used for ornamental highlights','Religious themes are common','Fine brushwork is central to the style']),
 it('Ganjifa Card Painting','Mysuru region','Hand-painted playing cards decorated with mythological, courtly or geometric imagery.',['Cards are individually painted','Mysore Ganjifa is a recognised regional tradition','Themes can include Hindu deities and courtly imagery','The tradition combines miniature painting with card making']),
 it('Chittara Art','Malnad, Karnataka','Decorative wall and floor art made with natural materials among communities of the Malnad region.',['Associated with the Deewaru community','Geometric patterns are prominent','Rice paste and natural pigments have been used traditionally','Art can decorate walls and floors during rituals and ceremonies']),
 it('Kasuti Embroidery','Northern Karnataka','Fine counted-thread embroidery creating geometric, floral and figurative motifs.',['Associated with Karnataka women’s textile traditions','Motifs include chariot, temple and floral forms','Stitches are worked carefully to preserve symmetry','Often seen on traditional garments and textiles']),
 it('Kaavi Art','Coastal Karnataka','Red-and-white incised wall decoration using laterite pigment and lime plaster.',['Found in parts of the Konkan and coastal Karnataka','Geometric and floral patterns are common','Used on homes and religious buildings','Shares historical techniques with coastal Goa']),
])
add('Kerala', [
 it('Kerala Mural Painting','Kerala','Temple and palace mural tradition using stylised figures, rich colours and narrative compositions.',['Major centres include historic temples and palaces','Themes are largely Hindu and mythological','Traditional pigments and prepared wall surfaces are used','Figures follow established Kerala mural conventions']),
 it('Kalamezhuthu','Kerala','Ritual floor drawing made from coloured powders to depict deities and sacred forms.',['Created directly on the floor','Natural powders are traditionally used','Kali and other deities are common subjects','The image is often ritually erased after the ceremony']),
 it('Theyyam Face Art','North Kerala','Highly elaborate facial painting and body decoration forming part of Theyyam performance.',['Face patterns vary by character','Natural and modern pigments may be used','Makeup works together with headdress and costume','It is part of a ritual performance rather than standalone painting']),
 it('Kathakali Makeup Art','Kerala','Codified face painting and makeup that visually identifies Kathakali characters.',['Colours communicate character types and qualities','Rice paste and natural pigments were traditionally important','The makeup is applied in stages before performance','It is integral to Kathakali’s visual storytelling']),
 it('Kalaripayattu Weapon & Body Design','Kerala','Traditional visual decoration of performance spaces and costumes associated with Kerala martial culture.',['Linked with the presentation of martial traditions','Symbols and costume vary among schools','Visual design supports ceremonial performance','Part of Kerala’s wider martial-arts heritage']),
])
add('Madhya Pradesh', [
 it('Gond Painting','Madhya Pradesh','Contemporary tribal painting tradition using rhythmic lines, dots and nature-inspired imagery.',['Strongly associated with Gond artists','Animals, trees and birds are frequent subjects','Fine dots and patterned lines create texture','Modern Gond artists work on paper and canvas']),
 it('Bhittichitra / Bhitti Art','Madhya Pradesh','Decorative wall painting traditions depicting local life, nature and religious themes.',['Walls provide a traditional canvas','Motifs vary by community','Natural earth pigments have been used historically','Art is linked with domestic and ceremonial spaces']),
 it('Pithora Painting','Western Madhya Pradesh','Ritual painting tradition associated with Bhil and Rathwa communities.',['Horses are central motifs','Paintings can mark vows and ceremonies','Traditionally made on prepared walls','The tradition is shared across parts of Gujarat and Madhya Pradesh']),
 it('Mandu Decorative Painting','Malwa region','Historic decorative painting and mural traditions connected with Malwa’s architectural heritage.',['Malwa has a long courtly and religious art history','Architectural surfaces carry ornamental motifs','Local traditions combine folk and courtly influences','Visual heritage survives in monuments and museums']),
 it('Bhil Painting','Western Madhya Pradesh','Tribal visual art using dots, animals, plants and scenes from community life.',['Associated with Bhil artists','Dot patterns create texture and movement','Nature is a major source of imagery','Styles vary between artists and regions']),
])
add('Maharashtra', [
 it('Warli Painting','Palghar & Thane region','Minimalist tribal painting built from geometric human, animal and nature forms.',['Associated with Warli communities','White rice-paste pigment is traditional','Circles, triangles and squares structure the figures','Themes include farming, dance, marriage and village life']),
 it('Paithani Design Art','Paithan & Yeola','Highly detailed silk textile art known for peacock motifs, borders and rich colour combinations.',['Associated with Paithan and Yeola','Peacock and floral motifs are characteristic','Design is created through handweaving rather than surface painting','The tradition has deep links with Maharashtra’s textile culture']),
 it('Chitrakathi Painting','Sawantwadi & Konkan','Narrative picture tradition using sequential painted images to accompany storytelling.',['Associated with the Konkan region','Pictures are shown as part of oral narratives','Themes include epics and local stories','Part of Maharashtra’s older itinerant storytelling traditions']),
 it('Sawantwadi Ganjifa Art','Sawantwadi','Hand-painted playing cards with mythological and decorative imagery.',['Sawantwadi is a major Ganjifa centre','Cards are painted individually','Themes include Dashavatara and other traditional subjects','The art combines miniature-style painting with card making']),
 it('Kaavi Art','Konkan Maharashtra','Red-and-white incised wall decoration found in historic houses and religious structures.',['Uses red laterite pigment and white lime','Geometric and floral motifs are common','Found across parts of the Konkan','Shares techniques with coastal Goa and Karnataka']),
])
add('Manipur', [
 it('Thang-Ta Visual Art','Manipur','Decorative and ceremonial visual traditions associated with the Meitei martial art Thang-Ta.',['Weapons and costume have distinctive visual forms','Training and performance have ceremonial dimensions','Tradition combines martial skill with movement and music','Visual elements vary by performance context']),
 it('Manipuri Pung Cholom Costume Art','Manipur','Colourful costume and visual presentation associated with Manipuri drum-dance performance.',['Pung Cholom combines drumming and movement','Costumes are designed for dynamic performance','Visual presentation is closely linked with Vaishnavite culture','Performance traditions are maintained in temples and cultural institutions']),
 it('Meitei Manuscript Illustration','Manipur','Illustrated manuscript traditions connected with Meitei literary and historical texts.',['Manuscripts preserve historical and religious knowledge','Illustration can accompany textual narratives','Traditional scripts and book forms are culturally important','The tradition is part of Meitei intellectual heritage']),
 it('Moirang Phee Pattern Art','Manipur','Decorative textile patterns created through traditional weaving associated with Moirang Phee.',['Moirang Phee is a recognised Manipuri textile tradition','Geometric and floral patterns are common','Design is created during weaving','The textiles are used for traditional garments and ceremonial purposes']),
])
add('Meghalaya', [
 it('Khasi & Jaintia Textile Art','Meghalaya','Traditional woven textile designs reflecting local dress, identity and community aesthetics.',['Weaving skills are transmitted within communities','Geometric and striped patterns are common','Textiles are used in ceremonial and everyday dress','Styles vary among Khasi, Jaintia and Garo communities']),
 it('Garo Textile Motif Art','Garo Hills','Decorative motifs woven into traditional Garo textiles and garments.',['Patterns are linked with community identity','Colour combinations vary by textile and occasion','Handweaving remains an important skill','Motifs appear in shawls, wraps and dress textiles']),
 it('Bamboo Decorative Art','Meghalaya','Bamboo is shaped and woven into visually distinctive baskets, mats and household objects.',['Bamboo is abundant in the region','Weaving techniques vary by community','Objects combine utility with decoration','Traditional patterns are often geometric']),
 it('Cane Pattern Art','Meghalaya','Cane weaving creates patterned furniture, baskets and domestic objects.',['Cane is processed and woven by hand','Fine openwork patterns are common','Craft is used in everyday life and interiors','Skills are passed through local artisan communities']),
 it('Traditional Wall Decoration','Meghalaya','Decorative painting and patterning used in homes, community spaces and festivals.',['Motifs reflect local environment and cultural identity','Materials vary with community and setting','Decoration is often seasonal or ceremonial','Contemporary artists continue to adapt traditional motifs']),
])
add('Mizoram', [
 it('Mizo Textile Motif Art','Mizoram','Distinctive woven patterns used in traditional Mizo garments and ceremonial textiles.',['Patterns identify textile traditions and communities','Handweaving is important to traditional dress','Colours and motifs vary among garments','Textiles carry social and ceremonial meaning']),
 it('Puanchei Design Art','Mizoram','Decorative textile art associated with the puanchei, a ceremonial Mizo wrap.',['Puanchei is an important traditional garment','Striped and geometric patterns are characteristic','Weaving and colour arrangement create the visual design','Often worn during important cultural occasions']),
 it('Bamboo Pattern Art','Mizoram','Bamboo weaving traditions producing baskets, mats and decorative forms with geometric patterns.',['Bamboo is widely available locally','Splitting and weaving are key techniques','Objects combine utility with visual pattern','Knowledge is transmitted through household and community practice']),
 it('Mizo Wood Carving','Mizoram','Carved wood used for household objects, architectural details and traditional decorative forms.',['Wood is shaped with hand tools','Motifs vary according to object and community','Traditional objects can have ceremonial significance','The craft reflects local material culture']),
])
add('Nagaland', [
 it('Naga Textile Motif Art','Nagaland','Bold woven patterns and colour combinations used in traditional Naga shawls and dress.',['Patterns can communicate community and social identity','Shawls are central to Naga textile culture','Motifs vary among Naga communities','Weaving remains an important traditional skill']),
 it('Naga Bead & Ornament Art','Nagaland','Decorative beadwork and traditional ornaments used in dress, ceremonies and identity display.',['Beads are combined with traditional garments','Colours and arrangements vary by community','Ornaments can indicate ceremonial or social context','Craft knowledge is passed through generations']),
 it('Naga Wood Carving','Nagaland','Decorative and architectural wood carving inspired by local motifs and traditional visual culture.',['Wood carving appears in traditional houses and objects','Animal and symbolic motifs are common','Carving is connected with community architecture','Styles vary among Naga groups']),
 it('Naga Folk Painting','Nagaland','Contemporary and traditional visual art inspired by Naga life, landscapes, symbols and community memory.',['Artists often draw on textile and tattoo motifs','Nature and village life are frequent subjects','Modern painters adapt traditional visual vocabulary','The art contributes to contemporary Naga cultural expression']),
])
add('Odisha', [
 it('Pattachitra','Puri & Raghurajpur','Traditional narrative painting on prepared cloth, known for controlled lines and religious imagery.',['Chitrakara artists are associated with the tradition','Jagannath and Vaishnavite themes are important','Cloth is prepared with a chalk-and-gum coating','Borders and ornamental details are characteristic']),
 it('Palm Leaf Engraving','Odisha','Illustrated and engraved palm-leaf art used for narrative, literary and decorative purposes.',['Palm leaves are dried and prepared before engraving','Lines are incised rather than simply painted','Black pigment can be rubbed into the engraved lines','Themes include mythology and literary stories']),
 it('Saura / Lanjia Saura Painting','Southern Odisha','Tribal wall and visual art using symbolic human, animal and ritual forms.',['Associated with Lanjia Saura communities','Geometric human figures are characteristic','Art can have ritual and communicative roles','Modern versions are also made on paper and canvas']),
 it('Odisha Tala Pattachitra','Odisha','Palm-leaf and manuscript-style visual art combining fine line work with narrative imagery.',['Uses prepared palm leaves','Fine incised lines create detailed figures','Themes include mythology and stories','Closely related to Odisha’s manuscript culture']),
 it('Dashavatara Ganjifa','Raghurajpur & Odisha','Hand-painted playing cards decorated with the ten avatars of Vishnu and other traditional imagery.',['Cards are painted individually','Dashavatara themes are especially associated with Odisha forms','The tradition combines game objects with miniature-style art','Raghurajpur is a major craft centre']),
])
add('Punjab', [
 it('Phulkari','Punjab','Silk-thread embroidery creating bold floral and geometric patterns on cloth.',['Traditionally worked on khaddar cloth','Brocade-like surface is created by counted stitches','Baugh and chope are well-known forms','Phulkari has strong ceremonial and domestic associations']),
 it('Punjabi Fresco & Haveli Painting','Punjab','Decorative wall painting tradition found historically in havelis and religious buildings.',['Floral and figurative motifs are common','Historic examples combine local and Persianate influences','Architectural surfaces are important canvases','Many surviving examples are preserved in heritage buildings']),
 it('Sanjhi Paper Art','Punjab/Braj cultural overlap','Intricate paper-cut devotional art centred on sacred and floral motifs.',['Made by cutting fine paper stencils','Often linked with Krishna devotion','The art is used for decorative and ritual display','The tradition has strong North Indian connections']),
 it('Punjabi Folk Embroidery','Punjab','Decorative needlework used on garments and household textiles.',['Floral and geometric motifs are common','Embroidery can be used for ceremonial clothing','Techniques vary by regional and community tradition','It remains part of Punjab’s textile visual culture']),
])
add('Rajasthan', [
 it('Phad Painting','Bhilwara & Shahpura region','Large narrative scroll painting traditionally used by Bhopas to tell the stories of Pabuji and Devnarayan.',['Traditionally painted on cloth','Bhopas narrate the story with song and performance','Pabuji and Devnarayan are major subjects','Natural pigments were traditionally important']),
 it('Pichwai Painting','Nathdwara','Devotional cloth painting created as a backdrop for Shrinathji, a form of Krishna.',['Originated in Nathdwara','Traditionally connected with Pushti Marg worship','Themes include Raslila, Annakuta and seasonal festivals','Fine detail, textile preparation and mineral pigments are characteristic']),
 it('Rajasthan Miniature Painting','Rajasthan courts','Highly detailed courtly and devotional painting traditions developed in several Rajput centres.',['Important schools include Mewar, Marwar, Bundi, Kota and Jaipur','Subjects include court life, hunting, battles and devotion','Fine brushes and detailed drawing are characteristic','Persian and Mughal influences shaped some court styles']),
 it('Kishangarh Painting','Kishangarh','Miniature school famous for idealised figures, poetic landscapes and the celebrated Bani Thani type.',['Flourished under Kishangarh court patronage','Radha-Krishna themes are prominent','Elongated facial features are characteristic','Nihal Chand is closely associated with the style']),
 it('Mewar Painting','Udaipur/Mewar','Rajput miniature tradition depicting religious stories, court life and local landscapes.',['Associated with the Mewar court','Udaipur was an important centre','Ramayana, Krishna themes and court scenes occur frequently','Strong colours and detailed line work are characteristic']),
 it('Marwar Painting','Jodhpur & Marwar','Courtly miniature painting tradition depicting rulers, ceremonies, battles, hunting and religious themes.',['Jodhpur was a major centre','Marwar style developed through Rajput court patronage','Portraits and court scenes are common','Mughal influence appears in some later works']),
 it('Mandana Art','Rajasthan','Geometric and symbolic floor and wall painting tradition made during festivals and household rituals.',['Traditionally made by women','White designs are often drawn over red or ochre surfaces','Motifs include animals, plants and geometric forms','Used during festivals and auspicious occasions']),
 it('Rajasthani Folk Art','Rajasthan','A broad family of regional folk visual traditions expressed through walls, textiles, painted objects and ritual designs.',['Styles vary by district and community','Folk themes include festivals, animals, deities and daily life','Natural earth pigments were traditionally common','Visual traditions are closely tied to domestic and ceremonial life']),
 it('Thewa Art','Pratapgarh','Intricate gold-on-glass art in which finely worked gold sheets are fused into coloured glass.',['Associated with Pratapgarh','Uses 23-carat gold in traditional work','Gold designs are placed on coloured glass','The technique is highly specialised and labour intensive']),
 it('Molela Terracotta Art','Molela, Rajsamand','Narrative terracotta plaques depicting deities, village life and folk themes.',['Molela is a major terracotta centre','Plaques are moulded and hand-finished','Ritual and devotional subjects are common','Traditional plaques are associated with shrine use and community practice']),
 it('Jaipur Blue Pottery Art','Jaipur','Glazed decorative art known for blue-and-white designs and a distinctive quartz-based body.',['Strongly associated with Jaipur','The body differs from ordinary clay pottery','Floral and geometric motifs are common','Objects are glazed and fired to create the finished surface']),
 it('Kathputli Art','Rajasthan','Handmade string puppets combining painted figures, costume, carving and traditional storytelling.',['Jaipur and Nagaur regions are associated with puppetry traditions','Puppets are traditionally carved and dressed by specialist makers','Stories are performed with music and narration','Kathputli is an important Rajasthani folk-theatre form']),
 it('Gota Patti Art','Rajasthan','Appliqué decoration using narrow metallic ribbon pieces stitched onto textiles.',['Common in festive and bridal textiles','Gold or silver-coloured gota is cut and stitched into motifs','Floral and geometric patterns are common','Jaipur and surrounding areas are known for the tradition']),
 it('Bandhani Art','Rajasthan','Tie-and-dye textile art producing dotted and patterned surfaces through tightly tied cloth.',['Major centres include Jaipur, Jodhpur and Sikar regions','Small tied points create characteristic patterns','Multiple dyeing stages can create multicolour designs','Used in odhnis, sarees, turbans and other garments']),
 it('Bagru Block Printing','Bagru, Jaipur district','Hand block printing tradition using carved wooden blocks, resist or direct printing and natural-dye methods.',['Bagru is a major printing centre','Indigo, madder and other natural dyes have traditional importance','Dabu resist printing is associated with the region','Floral and geometric repeats are common']),
 it('Sanganeri Block Printing','Sanganer, Jaipur','Fine hand block printing known for delicate floral, botanical and figurative motifs.',['Associated with Sanganer near Jaipur','Carved wooden blocks are used repeatedly','Fine floral patterns are characteristic','Both natural and modern dyes are used today']),
 it('Kundan Jewellery Art','Jaipur','Traditional jewellery setting technique in which gemstones are secured into finely prepared gold foil and lac foundations.',['Jaipur is a major centre','Kundan setting uses highly skilled stone-setting work','Polki and enamel techniques may appear in related jewellery','The craft has strong courtly and bridal associations']),
 it('Meenakari Art','Jaipur','Enamelling technique in which coloured glass-like enamel is fused onto metal jewellery and objects.',['Jaipur is a major Meenakari centre','Enamel colours are applied to prepared metal surfaces','Firing fixes the enamel to the metal','Often combined with Kundan jewellery techniques']),
])
add('Sikkim', [
 it('Thangka Painting','Sikkim monasteries','Buddhist devotional painting with prescribed iconography, proportions and symbolic colour use.',['Used in monasteries and Buddhist practice','Images follow established iconographic rules','Fine detail is essential','Tradition is shared across Himalayan Buddhist regions']),
 it('Buddhist Monastery Mural Art','Sikkim','Colourful sacred murals decorating monastery interiors and ritual spaces.',['Themes include Buddhist deities and narrative scenes','Murals form part of monastery architecture','Traditional pigments and detailed drawing are important','Visual art supports teaching and devotion']),
 it('Tibetan Buddhist Decorative Art','Sikkim','Decorative painting and pattern work associated with Himalayan Buddhist visual culture.',['Uses symbolic motifs such as lotus and clouds','Appears on ritual and architectural objects','Strongly connected with monastery culture','Styles reflect Tibetan Buddhist artistic conventions']),
 it('Sikkim Textile Motif Art','Sikkim','Traditional woven patterns used in ceremonial and community clothing.',['Textiles are important to several Sikkimese communities','Patterns and colours vary among communities','Handweaving preserves local design vocabulary','Ceremonial dress often carries distinctive motifs']),
])
add('Tamil Nadu', [
 it('Tanjore Painting','Thanjavur','Devotional painting known for rich colours, relief work and gold foil decoration.',['Originated in the Thanjavur region','Religious figures are common subjects','Gold foil and raised ornament create depth','The style developed under South Indian court and temple patronage']),
 it('Kalamkari of Srikalahasti','Tamil Nadu / Srikalahasti','Hand-drawn and block-assisted textile painting using narrative motifs and traditional dyeing processes.',['Srikalahasti is a major Kalamkari centre','Themes include Hindu epics and temple imagery','Natural-dye methods have a long history','Hand drawing with a kalam is a key feature']),
 it('Chola Bronze Visual Art','Tamil Nadu','Sculptural art tradition famous for highly refined bronze images of Hindu deities.',['Chola bronzes are especially famous for Nataraja images','Lost-wax casting is used','Icons follow established religious proportions','Bronze images were made for temple ritual and processions']),
 it('Kolam Art','Tamil Nadu','Daily and festival floor drawings made with rice flour or other powders in geometric and floral patterns.',['Common outside homes and public entrances','Women have traditionally maintained the practice','Designs can be highly symmetrical and mathematically structured','Festival kolams may be larger and more elaborate']),
 it('Kanchipuram Textile Design','Kanchipuram','Rich silk textile art known for contrasting borders, temple motifs and woven patterns.',['Associated with Kanchipuram silk sarees','Motifs include checks, stripes, temples and natural forms','Borders and body are often woven in contrasting colours','The design is created through the weaving structure']),
])
add('Telangana', [
 it('Cheriyal Painting','Cheriyal, Telangana','Narrative scroll painting tradition using bold colours and stylised figures to tell stories.',['Traditionally used by travelling storytellers','Themes include epics, folklore and village life','Figures are painted in a distinctive simplified style','Cheriyal is the recognised centre of the tradition']),
 it('Nirmal Painting','Nirmal, Telangana','Decorative painted art on wood and other surfaces, known for nature and mythological motifs.',['Associated with Nirmal town','Wooden surfaces are commonly used','Gold-like backgrounds and fine decorative work are characteristic','The tradition includes painted toys and furniture as well as panels']),
 it('Deccani Miniature Painting','Hyderabad & Deccan','Courtly miniature painting tradition associated with the Deccan Sultanates and Hyderabad.',['Developed in Deccan courts','Uses rich colour and decorative detail','Subjects include rulers, music, poetry and court life','Persianate and Indian influences interact in the style']),
 it('Dokra-inspired Decorative Art','Telangana tribal regions','Decorative metal imagery and figurines reflecting local tribal visual traditions.',['Uses traditional metalworking methods in some communities','Figures may depict animals, musicians and ritual themes','Visual vocabulary is linked with everyday and ceremonial life','Styles vary among artisan groups']),
 it('Telangana Folk Wall Art','Telangana','Decorative wall and floor painting traditions using geometric, floral and ritual motifs.',['Created in domestic and ceremonial settings','Local pigments and powders are traditional materials','Motifs vary by region and community','Festival decoration remains an important context']),
])
add('Tripura', [
 it('Reang / Bru Textile Motif Art','Tripura','Distinctive woven patterns and colours used in traditional dress among Indigenous communities.',['Textile patterns carry community identity','Handweaving remains important for traditional garments','Motifs and colours vary by community','Ceremonial clothing often has richer decoration']),
 it('Bamboo Pattern Art','Tripura','Bamboo weaving used to create patterned baskets, mats and decorative household forms.',['Bamboo is widely available','Weaving creates geometric surface patterns','Objects combine utility and visual design','Skills are commonly transmitted through families']),
 it('Wood Carving','Tripura','Carved wood used for household, decorative and community objects.',['Local wood is shaped with hand tools','Patterns vary by artisan and object','Carving is part of Tripura’s material culture','Decorative and practical objects are both produced']),
 it('Tribal Wall Decoration','Tripura','Visual decoration using geometric and natural motifs in community and domestic spaces.',['Motifs reflect local environment and cultural identity','Materials vary by community','Decoration can be seasonal or ceremonial','Traditional forms continue alongside contemporary art']),
])
add('Uttar Pradesh', [
 it('Banaras Mural Painting','Varanasi','Decorative and narrative mural tradition associated with historic buildings and religious spaces in Banaras.',['Varanasi has a long mural and painting history','Religious and floral motifs are common','Painted walls and ceilings are important surfaces','Modern artists continue to reinterpret the tradition']),
 it('Sanjhi Art','Mathura-Vrindavan','Intricate paper-cut devotional art centred on Krishna, Radha and sacred Braj imagery.',['Strongly associated with Braj','Made by cutting fine paper stencils','Often depicts Krishna’s sacred landscapes','Used for devotional and decorative display']),
 it('Miniature Painting of Lucknow','Lucknow','Courtly miniature and portrait painting traditions shaped by Awadhi and later Lucknow patronage.',['Developed under Awadh court culture','Portraits, court life and poetry are common themes','Persian and Indian artistic influences interact','Fine brushwork is characteristic']),
 it('Banarasi Textile Design Art','Varanasi','Highly detailed silk textile designs featuring brocade motifs and elaborate borders.',['Associated with Banarasi silk weaving','Metallic zari is often used','Floral buti and jaal patterns are characteristic','Design is built into the weave rather than painted on']),
 it('Agra Zardozi Art','Agra','Metal-thread embroidery creating raised floral and ornamental designs on textiles.',['Agra is a major zardozi centre','Metallic threads and embellishments are used','Bridal and ceremonial textiles are common products','The tradition has Mughal-era historical associations']),
])
add('Uttarakhand', [
 it('Aipan Art','Kumaon','White ritual floor and wall drawings made over red or ochre backgrounds.',['Strongly associated with Kumaon','Rice paste is traditionally used for white designs','Motifs include footprints, flowers and geometric forms','Used during festivals and household ceremonies']),
 it('Garhwal Miniature Painting','Garhwal','Pahari painting tradition associated with the former Garhwal court.',['Part of the wider Pahari miniature family','Religious and courtly themes are common','Fine line and colour work are characteristic','Garhwal patronage shaped the local style']),
 it('Jadupatya-inspired Scroll Art','Uttarakhand folk-art contexts','Narrative scroll and storytelling imagery found in Himalayan folk-art traditions.',['Pictures can support oral storytelling','Local landscapes and religious stories are common themes','Styles vary by community','The tradition reflects the close relationship between image and narration']),
 it('Ringaal Bamboo Art','Uttarakhand','Decorative basketry and patterned objects made from ringaal, a Himalayan bamboo.',['Ringaal is a local bamboo resource','Basketry combines utility and geometric pattern','Products include baskets, mats and containers','Craft knowledge is passed through artisan communities']),
 it('Wood Carving Art','Uttarakhand','Decorative carving used on traditional houses, temples, doors and household objects.',['Kumaoni and Garhwali buildings use carved wood details','Floral and geometric motifs are common','Religious buildings often have especially detailed carving','The craft is adapted to Himalayan timber architecture']),
])
add('West Bengal', [
 it('Bengal Patachitra','West Midnapore','Narrative scroll painting tradition in which images and songs together tell stories.',['Pingla is a major patachitra centre','Patua artists traditionally combine painting with sung narration','Stories include mythology, folklore and contemporary social themes','Cloth and paper surfaces are used']),
 it('Kalighat Painting','Kolkata','Urban folk painting tradition that developed around the Kalighat temple area in the 19th century.',['Originally sold to pilgrims and visitors','Bold brush lines and simplified figures are characteristic','Subjects included mythology and contemporary social life','The tradition influenced modern Indian art']),
 it('Krishnanagar Clay Art','Krishnanagar, Nadia','Highly detailed clay modelling of human figures, occupations and social scenes.',['Krishnanagar is a major centre','Figures are hand-modelled and finely finished','Realistic observation of people is a notable feature','The tradition includes figurines of everyday life']),
 it('Alpana Art','West Bengal','Decorative floor and ritual drawing made with rice paste and other traditional materials.',['White rice paste is a traditional medium','Used during puja, weddings and festivals','Floral and geometric motifs are common','Women have traditionally maintained the practice']),
 it('Bengal Scroll Painting','Bengal','Scroll-based visual storytelling tradition closely linked with Patua performance and oral narration.',['Images are arranged sequentially','Songs or spoken narration accompany the display','Themes can be mythological, social or contemporary','Patua communities preserve the tradition']),
])
add('Jammu & Kashmir', [
 it('Basohli Painting','Jammu region','Bold early Pahari miniature style known for strong colours, expressive faces and devotional themes.',['Associated with Basohli in the Jammu region','Developed strongly in the 17th–18th centuries','Krishna and Devi themes are common','Strong colour fields and distinctive faces are characteristic']),
 it('Kashmiri Papier-Mache Painting','Kashmir Valley','Highly decorative painted surface art on papier-mache objects using floral and ornamental motifs.',['Objects are shaped from papier-mache pulp','Surfaces are primed before detailed painting','Floral and arabesque designs are common','Kashmir is internationally known for this craft-art tradition']),
 it('Kashmiri Carpet Design','Kashmir Valley','Intricate floral and garden-inspired designs created through hand-knotting and drawing traditions.',['Persianate floral vocabulary is influential','Designs include boteh, floral sprays and garden layouts','Fine knotting allows detailed patterns','Designs are often planned from drawn patterns']),
 it('Kashmiri Sozni Embroidery','Kashmir Valley','Fine needle embroidery used to create delicate floral and paisley patterns on shawls and textiles.',['Uses very fine thread and small stitches','Paisley and floral motifs are common','Often worked on woollen or fine shawl fabrics','Requires highly skilled handwork']),
 it('Kashmiri Wood Carving','Kashmir Valley','Intricate carving used on walnut wood furniture, panels, doors and architectural objects.',['Walnut wood is especially associated with Kashmir carving','Floral and arabesque patterns are common','Carving ranges from shallow relief to deeper work','Furniture and architectural panels are major applications']),
])
add('Ladakh', [
 it('Ladakhi Thangka Painting','Ladakh monasteries','Buddhist devotional painting following established Himalayan iconographic rules.',['Used for teaching, meditation and ritual','Precise proportions are important','Monastic artists preserve the tradition','Visual vocabulary is shared with wider Tibetan Buddhist art']),
 it('Monastery Mural Art','Ladakh','Sacred murals decorating monastery halls, temples and ritual spaces with Buddhist narratives and symbols.',['Found in historic monasteries','Themes include deities, protectors and narrative cycles','Murals are part of the architecture','Traditional pigments and careful line work are important']),
 it('Wooden Decorative Art','Ladakh','Carved and painted wooden details used in monasteries, homes, furniture and religious objects.',['Wood is used for doors, pillars and furniture','Geometric and floral motifs are common','Buddhist symbols may appear in monastery work','Craft reflects adaptation to local materials']),
 it('Ladakhi Textile Motif Art','Ladakh','Decorative woven patterns used in woollen clothing, rugs and traditional household textiles.',['Wool is important in the high-altitude environment','Geometric motifs are common','Textile design is tied to practical cold-weather clothing','Patterns vary by community and object']),
])

# Add a generic fifth entry to states that have fewer than 5 only if needed.

# Find insertion point immediately before STATE_CRAFTS.
p=Path('/mnt/data/v9art/main.jsx')
s=p.read_text()
marker='const STATE_CRAFTS = {'
assert marker in s
entries=[]
for state, items in D.items():
    arr=[]
    for idx,x in enumerate(items,1):
        y=dict(x)
        y['source']='Government of India handicrafts records / Ministry of Culture / established art documentation'
        arr.append(y)
    entries.append((state,arr))
js='const STATE_ARTS = '+json.dumps(dict(entries), ensure_ascii=False, indent=2)+';\n\n'
s=s.replace(marker, js+marker, 1)
# Insert application loop before craft loop.
loop='''for (const [stateName, arts] of Object.entries(STATE_ARTS)) {\n  STATE_HIGHLIGHTS[stateName] ||= {};\n  STATE_HIGHLIGHTS[stateName].art = arts.map((item, index) => ({\n    id: `${stateName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-art-${index + 1}`,\n    title: item.title, short: item.short, image: null, place: item.place, period: 'Living art tradition',\n    medium: 'Traditional visual art', theme: 'Visual culture, storytelling and skilled practice',\n    description: item.description, facts: item.facts, gallery: [], source: item.source, verified: true, isArtHeritage: true\n  }));\n}\n\n'''
needle='for (const [stateName, crafts] of Object.entries(STATE_CRAFTS)) {'
assert needle in s
s=s.replace(needle, loop+needle,1)
p.write_text(s)
print('states',len(D),'entries',sum(map(len,D.values())))
