import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {onAuthStateChanged,signOut} from "firebase/auth";
import {collection,onSnapshot,addDoc,doc,setDoc,deleteDoc,updateDoc,serverTimestamp} from "firebase/firestore";
import {auth,db} from "./firebase-client.js";

const ADMINS=["sadik22319@gmail.com","rockysencr7@gmail.com"];
const CATS=["History","Monuments","Festivals","Arts & Crafts","People","Nature","Hidden Gems"];
const emptyHeritage={id:"",title:"",type:"",place:"",period:"",interest:"history",image:"",desc:"",facts:""};
const emptyFun={id:"",activity:"guess",category:"History",heritage:"",prompt:"",options:"",answer:"",reveal:"",clues:"",entries:""};
const isAdmin=u=>!!u?.email&&ADMINS.includes(u.email.toLowerCase());

function App(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(false),[tab,setTab]=useState("heritage"),[heritage,setHeritage]=useState([]),[fun,setFun]=useState([]),[reports,setReports]=useState([]),[hiddenGems,setHiddenGems]=useState([]),[hf,setHf]=useState(emptyHeritage),[ff,setFf]=useState(emptyFun),[msg,setMsg]=useState("");
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setReady(true)}),[]);
 useEffect(()=>{if(!isAdmin(user))return; const u1=onSnapshot(collection(db,"heritageContent"),s=>setHeritage(s.docs.map(d=>({id:d.id,...d.data()})))); const u2=onSnapshot(collection(db,"funFacts"),s=>setFun(s.docs.map(d=>({id:d.id,...d.data()})))); const u3=onSnapshot(collection(db,"userReports"),s=>setReports(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)))); const u4=onSnapshot(collection(db,"hiddenGemNominations"),s=>setHiddenGems(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)))); return()=>{u1();u2();u3();u4()}},[user]);
 if(!ready)return <div className="denied">Loading Admin Panel…</div>;
 if(!user)return <div className="denied"><h1>Admin access</h1><p>Please sign in with an authorised Living India admin account.</p><a className="back" href="./login.html">← Go to Login</a></div>;
 if(!isAdmin(user))return <div className="denied"><h1>Access denied</h1><p>This account is not authorised to manage Living India.</p><a className="back" href="./index.html">← Back to Living India</a></div>;
 const notice=x=>{setMsg(x);setTimeout(()=>setMsg(""),2500)};
 const saveHeritage=async e=>{e.preventDefault(); if(!hf.id.trim()||!hf.title.trim())return notice("ID and title are required."); const id=hf.id.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-"); await setDoc(doc(db,"heritageContent",id),{...hf,id, facts:hf.facts.split("\n").map(x=>x.trim()).filter(Boolean),updatedAt:serverTimestamp(),updatedBy:user.email},{merge:true}); setHf(emptyHeritage);notice("Heritage saved to Firebase.")};
 const saveFun=async e=>{e.preventDefault(); if(!ff.id.trim()||!ff.activity)return notice("ID and activity are required."); const id=ff.id.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-"); const data={...ff,activity:tab,id,options:ff.options.split("\n").map(x=>x.trim()).filter(Boolean),clues:ff.clues.split("\n").map(x=>x.trim()).filter(Boolean),entries:ff.entries?JSON.parse(ff.entries):[],updatedAt:serverTimestamp(),updatedBy:user.email}; await setDoc(doc(db,"funFacts",id),data,{merge:true});setFf(emptyFun);notice("Fun Fact challenge saved.")};
 const editH=x=>setHf({...emptyHeritage,...x,facts:Array.isArray(x.facts)?x.facts.join("\n"):x.facts||""});
 const editF=x=>setFf({...emptyFun,...x,options:Array.isArray(x.options)?x.options.join("\n"):x.options||"",clues:Array.isArray(x.clues)?x.clues.join("\n"):x.clues||"",entries:x.entries?JSON.stringify(x.entries,null,2):""});
 const remove=async(type,id)=>{if(!confirm("Delete this Firebase record?"))return;await deleteDoc(doc(db,type,id));notice("Deleted from Firebase.")};
 const reviewHiddenGem=async(id,status)=>{ const action=status==="approved"?"approve":"reject"; if(!confirm(`Are you sure you want to ${action} this nomination?`))return; try{await updateDoc(doc(db,"hiddenGemNominations",id),{status,reviewedBy:user.email,reviewedAt:serverTimestamp(),...(status==="approved"?{approvedAt:serverTimestamp(),approvedBy:user.email}:{})});notice(`Nomination ${status}.`)}catch(error){console.error(error);notice("Could not update nomination.")}};
 return <div className="admin-wrap"><header className="admin-head"><div><div className="admin-brand">LIVING <b>INDIA</b> · Admin</div><div className="admin-user">Signed in as {user.email}</div></div><div><a className="back" href="./index.html">← Website</a> &nbsp; <button className="admin-btn" onClick={()=>signOut(auth)}>Sign out</button></div></header>
 <div className="admin-tabs">{[["hidden-gems","Hidden Gems"],["heritage","Heritage"],["guess","Guess"],["mystery","Mystery"],["puzzle","Crossword"],["reports","Reports"]].map(([id,l])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{l}</button>)}</div>
 {msg&&<div className="status">{msg}</div>}
 {tab==="hidden-gems"&&<div className="admin-grid"><Panel title={`Hidden Gems — Nomination Reviews (${hiddenGems.filter(x=>x.status==="pending").length} pending)`}><div className="admin-note">Nominations submitted by users are stored in Firebase with <code>pending</code> status. Nothing is published until an authorised admin approves it.</div><div className="hg-admin-list">{hiddenGems.length?hiddenGems.map(x=><div className={`hg-admin-card status-${x.status||"pending"}`} key={x.id}>{x.photoUrl&&<img src={x.photoUrl} alt=""/>}<div className="hg-admin-info"><div className="hg-admin-top"><strong>{x.name}</strong><span>{String(x.status||"pending").toUpperCase()}</span></div><p><b>{x.category}</b> · {x.district}, {x.state}</p><p>{x.story}</p><small>Nominated by {x.nominatorEmail||"community user"}{x.createdAt?.toDate?` · ${x.createdAt.toDate().toLocaleString()}`:""}</small><div className="admin-item-actions">{x.status!=="approved"&&<button className="admin-btn primary" onClick={()=>reviewHiddenGem(x.id,"approved")}>✓ Approve</button>}{x.status!=="rejected"&&<button className="admin-btn danger" onClick={()=>reviewHiddenGem(x.id,"rejected")}>✕ Reject</button>}{x.status!=="pending"&&<button className="admin-btn" onClick={()=>remove("hiddenGemNominations",x.id)}>Delete</button>}</div></div></div>):<div className="admin-empty">No nominations yet.</div>}</div></Panel></div>}
 {tab==="heritage"&&<div className="admin-grid"><Panel title="Add / Edit Heritage"><form className="admin-form" onSubmit={saveHeritage}><div className="admin-row"><label>ID<input value={hf.id} onChange={e=>setHf({...hf,id:e.target.value})} placeholder="e.g. konark-sun-temple"/></label><label>Title<input value={hf.title} onChange={e=>setHf({...hf,title:e.target.value})}/></label></div><div className="admin-row"><label>Type<input value={hf.type} onChange={e=>setHf({...hf,type:e.target.value})}/></label><label>Place<input value={hf.place} onChange={e=>setHf({...hf,place:e.target.value})}/></label></div><div className="admin-row"><label>Period<input value={hf.period} onChange={e=>setHf({...hf,period:e.target.value})}/></label><label>Interest<select value={hf.interest} onChange={e=>setHf({...hf,interest:e.target.value})}><option>history</option><option>architecture</option><option>art</option><option>craft</option><option>music</option><option>performance</option><option>festival</option><option>food</option><option>language</option><option>ritual</option></select></label></div><label>Image URL<input value={hf.image} onChange={e=>setHf({...hf,image:e.target.value})}/></label><label>Description<textarea value={hf.desc} onChange={e=>setHf({...hf,desc:e.target.value})}/></label><label>Facts (one per line)<textarea value={hf.facts} onChange={e=>setHf({...hf,facts:e.target.value})}/></label><button className="admin-btn primary">Save to Firebase</button></form></Panel><List title="Firebase Heritage Records" items={heritage} edit={editH} remove={id=>remove("heritageContent",id)}/></div>}
 {tab!=="heritage"&&tab!=="reports"&&<div className="admin-grid"><Panel title={`Add / Edit ${tab==="puzzle"?"Crossword":tab[0].toUpperCase()+tab.slice(1)}`}><div className="admin-note">For Crossword, <b>entries</b> must be a JSON array like <code>[{"{\"word\":\"HARAPPA\",\"row\":0,\"col\":0,\"dir\":\"across\",\"clue\":\"Ancient city\"}"}]</code>. Rows and columns are zero-based.</div><form className="admin-form" onSubmit={saveFun}><div className="admin-row"><label>ID<input value={ff.id} onChange={e=>setFf({...ff,id:e.target.value})}/></label><label>Category<select value={ff.category} onChange={e=>setFf({...ff,category:e.target.value})}>{CATS.map(c=><option key={c}>{c}</option>)}</select></label></div><label>Heritage<input value={ff.heritage} onChange={e=>setFf({...ff,heritage:e.target.value})}/></label><label>Prompt<input value={ff.prompt} onChange={e=>setFf({...ff,prompt:e.target.value})}/></label>{tab==="guess"&&<><label>Options (one per line)<textarea value={ff.options} onChange={e=>setFf({...ff,options:e.target.value})}/></label><label>Correct Answer<input value={ff.answer} onChange={e=>setFf({...ff,answer:e.target.value})}/></label></>}{tab==="mystery"&&<><label>Clues (one per line)<textarea value={ff.clues} onChange={e=>setFf({...ff,clues:e.target.value})}/></label><label>Answer<input value={ff.answer} onChange={e=>setFf({...ff,answer:e.target.value})}/></label></>}{tab==="puzzle"&&<label>Crossword Entries JSON<textarea className="jsonbox" value={ff.entries} onChange={e=>setFf({...ff,entries:e.target.value})} placeholder='[{"word":"TAJMAHAL","row":0,"col":0,"dir":"across","clue":"White marble monument"}]'/></label>}<label>Reveal / Explanation<textarea value={ff.reveal} onChange={e=>setFf({...ff,reveal:e.target.value})}/></label><input type="hidden" value={ff.activity} /><button className="admin-btn primary">Save Challenge</button></form></Panel><List title="Firebase Challenges" items={fun.filter(x=>x.activity===tab)} edit={editF} remove={id=>remove("funFacts",id)}/></div>}
 {tab==="reports"&&<Panel title="User Reports"><div className="admin-note">Reports are visible only to the two authorised admin emails. This panel reads the existing <code>userReports</code> collection.</div>{reports.length?reports.map(r=><div className="report" key={r.id}><strong>{r.subject||"User report"}</strong><div>{r.userEmail||r.email||r.userId||"Unknown user"}</div><pre>{r.message||r.description||""}</pre><small>{r.createdAt?.toDate?r.createdAt.toDate().toLocaleString():""}</small></div>):<div className="admin-empty">No reports yet.</div>}</Panel>}
 </div>}
function Panel({title,children}){return <section className="admin-panel"><h2>{title}</h2>{children}</section>}
function List({title,items,edit,remove}){return <section className="admin-panel"><h2>{title}</h2><div className="admin-list">{items.length?items.map(x=><div className="admin-item" key={x.id}><strong>{x.title||x.heritage||x.id}</strong><small>{x.id} · {x.category||x.place||x.activity}</small><div className="admin-item-actions"><button className="admin-btn" onClick={()=>edit(x)}>Edit</button><button className="admin-btn danger" onClick={()=>remove(x.id)}>Delete</button></div></div>):<div className="admin-empty">No Firebase records yet.</div>}</div></section>}

createRoot(document.getElementById("admin-root")).render(<App/>);
